include:
  - component: $CI_SERVER_FQDN/components/sast/sast@~latest
  - component: $CI_SERVER_FQDN/components/dependency-scanning/main@~latest
  - component: $CI_SERVER_FQDN/components/code-quality-oss/codequality-os-scanners-integration/pmd@~latest

default:
  image: eclipse-temurin:17-jdk

variables:
  DEFAULT_GRADLE_CLI_ARGS: "--info --stacktrace"

stages:
  - build
  - test

.template:
  artifacts:
    paths:
      - build
      - .gradle
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - build
      - .gradle

build:
  extends: .template
  stage: build
  script:
    - echo "Beginning build..."
    - ./gradlew assemble $DEFAULT_GRADLE_CLI_ARGS
    - echo "Build completed..."

test:
  extends: .template
  stage: test
  script:
    - echo "Running tests..."
    - ./gradlew check $DEFAULT_GRADLE_CLI_ARGS
    - echo "Tests completed..."
  artifacts:
    reports:
      junit: build/test-results/**/*.xml
      coverage_report:
        coverage_format: jacoco
        path: build/jacoco/*.xml
