include:
  - component: $CI_SERVER_FQDN/components/sast/sast@~latest
  - component: $CI_SERVER_FQDN/components/dependency-scanning/main@~latest
  - component: $CI_SERVER_FQDN/components/code-quality-oss/codequality-os-scanners-integration/pmd@~latest

default:
  image: eclipse-temurin:17-jdk

variables:
  DEFAULT_GRADLE_CLI_ARGS: "--info --stacktrace"

stages:
  - build
  - test

.template:
  artifacts:
    paths:
      - build
      - .gradle
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - build
      - .gradle

build:
  extends: .template
  stage: build
  script:
    - echo "Beginning build..."
    - ./gradlew generateLock saveLock
    - ./gradlew assemble $DEFAULT_GRADLE_CLI_ARGS
    - echo "Build completed..."
  # generateLock saves the lock file in the build/ directory of a project
  # and saveLock copies it into the root of a project. To avoid duplicates
  # and get an accurate location of the dependency, use find to remove the
  # lock files in the build/ directory only.
  after_script:
    - find . -path '*/build/dependencies.lock' -print -delete
  # Collect all dependencies.lock artifacts and pass them onto jobs
  # in sequential stages.
  artifacts:
    paths:
      - "**/dependencies.lock"

test:
  extends: .template
  stage: test
  script:
    - echo "Running tests..."
    - ./gradlew check $DEFAULT_GRADLE_CLI_ARGS
    - echo "Tests completed..."
  artifacts:
    reports:
      junit: build/test-results/**/*.xml
      coverage_report:
        coverage_format: jacoco
        path: build/jacoco/*.xml
