{
 "title": "Grafana + Prometheus Demo",
 "description": "Dashboard for Spring Boot2 Statistics(by micrometer-prometheus).",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{instance=\"$application\"}[1m])) / sum(rate(http_server_requests_seconds_count{instance=\"$application\"}[1m]))",
       "legendFormat": "Time"
      }
     ]
    },
    {
     "title": "Requests per Minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (increase(http_server_requests_seconds_count{instance=\"$application\"}[1m]))",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Errors per Minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (increase(http_server_requests_seconds_count{instance=\"$application\", exception!=\"None\"}[1m]))",
       "legendFormat": "{{uri}}{action={{action}}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(system_cpu_usage{instance=\"$application\"})",
       "legendFormat": "System"
      },
      {
       "expr": "avg(process_cpu_usage{instance=\"$application\"})",
       "legendFormat": "User"
      }
     ]
    },
    {
     "title": "Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{instance=\"$application\", area=\"heap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{instance=\"$application\", area=\"heap\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Non-Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{instance=\"$application\", area=\"nonheap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{instance=\"$application\", area=\"nonheap\"})",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "G1 Eden Space (heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$application\", id=\"G1 Eden Space\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$application\", id=\"G1 Eden Space\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$application\", id=\"G1 Eden Space\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "G1 Old Gen (heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$application\", id=\"G1 Old Gen\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$application\", id=\"G1 Old Gen\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$application\", id=\"G1 Old Gen\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "G1 Survivor Space (heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$application\", id=\"G1 Survivor Space\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$application\", id=\"G1 Survivor Space\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$application\", id=\"G1 Survivor Space\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Code Cache (non-heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$application\", id=\"Code Cache\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$application\", id=\"Code Cache\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$application\", id=\"Code Cache\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Compressed Class Space (non-heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$application\", id=\"Compressed Class Space\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$application\", id=\"Compressed Class Space\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$application\", id=\"Compressed Class Space\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Metaspace (non-heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$application\", id=\"Metaspace\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$application\", id=\"Metaspace\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$application\", id=\"Metaspace\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$application\", cf_instance_number=\"$instance\"}[5m])",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$application\", id=\"direct\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$application\", id=\"direct\"}",
       "legendFormat": "Capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$application\", id=\"mapped\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$application\", id=\"mapped\"}",
       "legendFormat": "Capacity"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$application\", cf_instance_number=\"$instance\"}[5m])",
       "legendFormat": "Allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$application\", cf_instance_number=\"$instance\"}[5m])",
       "legendFormat": "Promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GC Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$application\", cf_instance_number=\"$instance\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$application\", cf_instance_number=\"$instance\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(method, status, uri, action) (irate(http_server_requests_seconds_count{instance=\"$application\", uri!~\".*(actuator|cloudfoundryapplication).*\"}[5m]))",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}{action={{action}}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(method, status, uri, action) (irate(http_server_requests_seconds_sum{instance=\"$application\", exception=\"None\", uri!~\".*(actuator|cloudfoundryapplication).*\"}[5m])) / sum by(method, status, uri, action) (irate(http_server_requests_seconds_count{instance=\"$application\", exception=\"None\", uri!~\".*(actuator|cloudfoundryapplication).*\"}[5m]))",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Error Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tomcat_global_error_total{instance=\"$application\", cf_instance_number=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 4, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tomcat_threads_current_threads{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Current thread"
      },
      {
       "expr": "tomcat_threads_busy_threads{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Current thread busy"
      }
     ]
    },
    {
     "title": "Sent & Recieved Bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(tomcat_global_sent_bytes_total{instance=\"$application\", cf_instance_number=\"$instance\"}[5m])",
       "legendFormat": "Sent"
      },
      {
       "expr": "irate(tomcat_global_received_bytes_total{instance=\"$application\", cf_instance_number=\"$instance\"}[5m])",
       "legendFormat": "Recieved"
      }
     ]
    },
    {
     "title": "Thread Config Max",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tomcat_threads_config_max_threads{instance=\"$application\", cf_instance_number=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Datasource Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "agencyAdmin DataSource",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "agencyAdmin_connections_active{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "agencyAdmin_connections_max{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "claims DataSource",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "claims_connections_active{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "claims_connections_max{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "default DataSource (jndi)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jndi_connections_active{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "jndi_connections_max{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "lockout DataSource",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "lockoutEcommerce_connections_active{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "lockoutEcommerce_connections_max{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "prefill DataSource",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prefillJndi_connections_active{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "prefillJndi_connections_max{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "renewals DataSource",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "renewals_connections_active{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "renewals_connections_max{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "sigTracking DataSource",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sigTracking_connections_active{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "sigTracking_connections_max{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "xlTransaction DataSource",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "xlTransaction_connections_active{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "xlTransaction_connections_max{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Session Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Circuit Status",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fault_tolerant_sessions_circuit{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 4, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fault_tolerant_sessions_active_sessions{instance=\"$application\", cf_instance_number=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Average Session Length",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "fault_tolerant_sessions_time_milliseconds{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "{{quantile}}"
      },
      {
       "expr": "fault_tolerant_sessions_time_milliseconds_max{instance=\"$application\", cf_instance_number=\"$instance\"}",
       "legendFormat": "1.0"
      }
     ]
    },
    {
     "title": "Session Events [1m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(action) (rate(fault_tolerant_sessions_events_seconds_count{instance=\"$application\", action!=\"GET\", cf_instance_number=\"$instance\"}[1m]))",
       "legendFormat": "{{action}}"
      },
      {
       "expr": "sum by(action, cache) (rate(fault_tolerant_sessions_events_seconds_count{instance=\"$application\", action=\"GET\", cf_instance_number=\"$instance\"}[1m]))",
       "legendFormat": "{{action}} - CACHE {{cache}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Logging Events",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$application\", level=\"error\"}[5m])",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      },
      {
       "expr": "irate(logback_events_total{instance=\"$application\", level=\"warn\"}[5m])",
       "legendFormat": "warn"
      },
      {
       "expr": "irate(logback_events_total{instance=\"$application\", level=\"info\"}[5m])",
       "legendFormat": "info"
      },
      {
       "expr": "irate(logback_events_total{instance=\"$application\", level=\"debug\"}[5m])",
       "legendFormat": "debug"
      },
      {
       "expr": "irate(logback_events_total{instance=\"$application\", level=\"trace\"}[5m])",
       "legendFormat": "trace"
      }
     ]
    }
   ]
  }
 ]
}