com:
  shelter:
    launchdarkly:
      enabled: false
      sdk-key:  # Intentionally left out, but can be updated to use your own SDK key and your own LD Project
spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include: '*'